name: Run php tests
on:
  push:
    branches:

jobs:
  test:
    if: |
      !(github.event_name == 'push' && contains(github.event.head_commit.message, '[skip ci]')) &&
      !(github.event_name == 'pull_request' && contains(join(github.event.pull_request.title, github.event.pull_request.body), '[skip ci]'))
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          tools: composer:v1

      - name: Install dependencies
        run: composer install

      - name: Run phpunit
        run: php vendor/bin/phpunit --coverage-text

      - name: Run phpcs
        run: php vendor/bin/phpcs --standard=PSR2 src/Makaira/

      - name: Run phpmd
        run: php vendor/bin/phpmd src/Makaira/ text codesize,design
